apiVersion: v2
name: trino
description: A Helm chart for Trino that wraps the official Trino chart
type: application
version: 1.0.0
appVersion: "latest"

dependencies:
  - name: trino
    version: "1.42.1"
    repository: https://trinodb.github.io/charts
