apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow3
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $values/apps/airflow3/values.yaml

    - repoURL: https://github.com/ysnpr/charts.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow3

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true