# apps/airflow/values.yaml

airflow:
  postgresql:
    enabled: true

  redis:
    enabled: true

  createUserJob:
    useHelmHooks: false

  migrateDatabaseJob:
    useHelmHooks: false

  config:
    core:
      load_examples: true