# apps/airflow3/values.yaml

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  enabled: true  
  useHelmHooks: false
  applyCustomEnv: false
  jobAnnotations:
      "argocd.argoproj.io/hook": Sync

config:
  core:
    load_examples: "true"
  api:
    expose_config: "true"

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "True"