# apps/airflow/values.yaml

postgresql:
  enabled: true

redis:
  enabled: true

createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false

config:
  core:
    load_examples: "true"
  api:
    expose_config: "true"

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "True"